version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend/src:/workspace
      # - ~/.gitconfig:/root/.gitconfig
    # ports:
    #   - 9080:9080
    # command: sleep infinity
