# Use postgres/example user/password credentials
version: '3'

volumes:
  pgdata:
    driver: local

services:
  backend:
    build: backend
    container_name: backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/workspace
    working_dir: /workspace
    command: sleep infinity
    # tty: true
  db:
    build: db
    container_name: database
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD=postgres
      - POSTGRES_DB=appdb
      - DATABASE_HOST=localhost
      # エンコーディングを指定しておく
      # initdbで指定できる内容はここで指定可能
      # https://www.postgresql.org/docs/10/static/app-initdb.html を参照。
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale='C'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # - ${PWD}/db/data:/var/lib/postgresql/data
      # - `pwd`/db/init:/docker-entrypoint-initdb.d
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
